services:
  mongo-customers:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_customer_data:/data/db

  mysql-hotel:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql_hotel_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  mysql-room:
    image: mysql:latest
    ports:
      - 3307:3306
    volumes:
      - mysql_room_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  product-service:
    depends_on:
      - mongo-customers
    image: eliasgps/customer-service
    ports:
      - 8080:8080
    links:
      - mongo-customers
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-customers

  room-service:
    depends_on:
      - mysql-room
    image: eliasgps/room-service
    ports:
      - 8082:8082
    links:
      - mysql-room
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-room
      MYSQL_DB_PORT: 3307

  hotel-service:
    depends_on:
      - room-service
    image: eliasgps/hotel-service
    ports:
      - 8081:8081
    environment:
      CUSTOMER_SERVICE_BASEURL: customer-service:8080
      ROOM_INFO_SERVICE_BASEURL: room-service:8082
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-hotel
      MYSQL_DB_PORT: 3306

  api-gateway:
    depends_on:
      - customer-service
      - hotel-service
    image: eliasgps/ede-api-gateway
    ports:
      - 8083:8083
    links:
      - customer-service
      - hotel-service
    environment:
      PRODUCT_SERVICE_BASEURL: product-service:8080
      HOTEL_SERVICE_BASEURL: hotel-service:8081

volumes:
  mongodb_customer_data:
  mysql_room_data:
  mysql_hotel_data:
