apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-hotel
  name: mysql-hotel
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql-hotel
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/project-default: "true"
        io.kompose.service: mysql-hotel
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: abc123
          image: mysql:latest
          name: mysql-hotel
          ports:
            - containerPort: 3306
              hostPort: 3306
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-hotel-data
      restartPolicy: Always
      volumes:
        - name: mysql-hotel-data
          persistentVolumeClaim:
            claimName: mysql-hotel-data
status: {}
