server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid, profile, email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: hotel-service
          uri: http://${HOTEL_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/hotels
            - Method=GET
          filters:
            - SetPath=/api/hotel
        - id: room-service
          uri: http://${ROOM_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/rooms
            - Method=GET
          filters:
            - SetPath=/api/room
        - id: customer-service
          uri: http://${CUSTOMER_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/customers
            - Method=GET
          filters:
            - SetPath=/api/customer
