server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  cloud:
    gateway:
      routes:
        - id: hotel-service
          uri: http://${HOTEL_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/hotels
          filters:
            - SetPath=/api/hotel
        - id: room-service
          uri: http://${ROOM_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/rooms
          filters:
            - SetPath=/api/room
        - id: customer-service
          uri: http://${CUSTOMER_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/customers
            - Method=GET
          filters:
            - SetPath=/api/customer