server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid, profile, email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        # GET HOTELS
        - id: hotel-service-all
          uri: http://${HOTEL_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/hotels
            - Method=GET
          filters:
            - SetPath=/api/hotel
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 1
#                redis-rate-limiter.requestedToken: 1

        # POST HOTEL
        - id: hotel-service-create
          uri: http://${HOTEL_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/hotels
            - Method=POST
          filters:
            - SetPath=/api/hotel

        # PUT HOTEL
        - id: hotel-service-update
          uri: http://${HOTEL_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/hotels/{id}
            - Method=PUT
          filters:
            - SetPath=/api/hotel/{id}

        # DELETE HOTEL
        - id: hotel-service-delete
          uri: http://${HOTEL_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/hotels/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/hotel/{id}

        # GET ROOMS
        - id: room-service-all
          uri: http://${ROOM_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/rooms
            - Method=GET
          filters:
            - SetPath=/api/room
        # GET CUSTOMERS
        - id: customer-service-all
          uri: http://${CUSTOMER_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/customers
            - Method=GET
          filters:
            - SetPath=/api/customer
