apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-customers
  name: mongo-customers
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-customers
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/project-default: "true"
        io.kompose.service: mongo-customers
    spec:
      containers:
        - image: mongo:latest
          name: mongo-customers
          ports:
            - containerPort: 27017
              hostPort: 27017
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-customer-data
      restartPolicy: Always
      volumes:
        - name: mongodb-customer-data
          persistentVolumeClaim:
            claimName: mongodb-customer-data
status: {}
